name: Deploy Laravel Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout del código del repositorio
      uses: actions/checkout@v2

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: 'composer'
        
    - name: Instalar dependencias de Composer
      run: composer install --no-dev --optimize-autoloader

    - name: Cambiar permisos de storage y bootstrap/cache
      run: |
        chmod -R 775 storage bootstrap/cache

    - name: Configurar Laravel para producción
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Configurar el archivo .env
      run: |
        cp .env.example .env   
        php artisan key:generate     

    - name: Subir al servidor via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_DESTINATION }}
    
    - name: Configurar Laravel post-deployment
      run: |
        php artisan migrate --force